English translations
Linkkijkl/linkki-web pull request #170
Opened 2024-06-17 21:32 UTC by lurppa

A bunch of translations for keskustelukanavat, yhteistyö, equipment rental, tenttiarkisto, haalarimerkit and hallitus.

Closes #108 closes #109 closes #110 closes #140

2024-06-17 21:57 UTC, ikaros02 requested changes
Pari typoa tms. löysin

Kiitos kovasta työstäsi myös tänään 🙏

2024-06-17 21:57 UTC, ikaros02 commented on content/hallitus/_index.en.md
> +**Communicator** maintains mialing lists and acts as a contact person alongside the Chairperson.
mialing -> mailing

2024-06-17 21:57 UTC, ikaros02 commented on content/toiminta/keskustelukanavat.en.md
> +- **Telegram**: @linkkijk**l
onko tässä ** tarkoituksella keskellä tägiä

2024-06-18 10:04 UTC, lurppa commented on content/toiminta/keskustelukanavat.en.md
> +- **Telegram**: @linkkijk**l
Ei, fiksattu

2024-06-18 10:05 UTC, lurppa commented on content/hallitus/_index.en.md
> +**Communicator** maintains mialing lists and acts as a contact person alongside the Chairperson.
Fixed

2024-06-18 10:35 UTC, ikaros02 approved these changes
Jätte bra :-)

2024-06-18 22:21 UTC, merged